apiVersion: v1
kind: Service
metadata:
  name: rabbit-service
  namespace: default
spec:
  selector:
    # matches with Deployment spec.selector.matchLabels
    app: rabbit
  ports:
    - port: 5672
      targetPort: 5672