apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: co2-sensor
  name: co2-sensor
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: co2-sensor
    spec:
      containers:
      - image: co2-sensor
        name: co2-sensor
        ports:
        - containerPort: 3001
        resources: {}
      restartPolicy: Always
status: {}
