version: '3'

networks:
  isolation-network:
    driver: bridge

volumes:
  cassandra-volume:

services:
  tasker:
    container_name: tasker
    restart: always # if it fails, it attempts to restart the node
    image: ubervelocity/tasker:1.0
    ports:
      - '5000:5000'
    networks:
      - isolation-network
    depends_on:
      - mongo-node
    
  mongo-node:
    container_name: mongo-node
    image: mongo:4.0.4
    ports:
      - '27017:27017'
    networks:
      - isolation-network

  front-end:
    container_name: front-end
    restart: always
    image: ubervelocity/front-end:1.0
    ports:
      - '80:80'
    networks:
      - isolation-network

  history-retriever:
    container_name: history
    restart: always
    image: ubervelocity/history:1.0
    ports:
      - '4002:4002'
    networks:
      - isolation-network

  chat:
    container_name: chat
    restart: always
    image: ubervelocity/chat:1.0
    ports:
      - '4001:4001'
    networks:
      - isolation-network

  cassandra-cluster:
    container_name: cassandra-cluster
    restart: always
    image: cassandra:3.0
    networks:
      - isolation-network
    volumes:
      - cassandra-volume:/var/lib/cassandra
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160

  gw-sensor:
    container_name: gw-sensor
    restart: always
    image: ubervelocity/gw:1.0
    ports:
      - '3002:3002'
    networks:
      - isolation-network
    depends_on:
      - mongo-node
    
  co2-sensor:
    container_name: co2-sensor
    restart: always
    image: ubervelocity/co2:1.0
    ports:
      - '3001:3001'
    networks:
      - isolation-network
    depends_on:
      - mongo-node

  ingest:
    container_name: ingest
    restart: always
    image: ubervelocity/ingest:1.0
    ports:
      - '4003:4003'
    networks:
      - isolation-network
  
  rabbit:
    container_name: rabbit
    restart: always
    image: rabbitmq:3
    hostname: rabbit
    ports:
      - '5672:5672'
    networks:
      - isolation-network
  
  packager:
    container_name: packager
    restart: always
    image: ubervelocity/packager:1.0
    ports:
      - '4004:4004'
    networks:
      - isolation-network
    depends_on:
      - mongo-node
      - cassandra-cluster