version: '3'

networks:
  isolation-network:
    driver: bridge

services:
  tasker:
    container_name: tasker
    restart: always # if it fails, it attempts to restart the node
    build: tasker/backend
    ports:
      - '5000:5000'
    links: # links tasker to database
      - mongo-node
    networks:
      - isolation-network
    
  mongo-node:
    container_name: mongo-node
    image: mongo:4.0.4
    ports:
      - '27017:27017'
    networks:
      - isolation-network

  front-end:
    container_name: front-end
    restart: always
    build: tasker/frontend
    ports:
      - '80:80'
    networks:
      - isolation-network

  history-retriever:
    container_name: history
    restart: always
    build: history_retriever
    ports:
      - '4002:4002'
    networks:
      - isolation-network

  chat:
    container_name: chat
    restart: always
    build: chat
    ports:
      - '4001:4001'
    networks:
      - isolation-network
  
  cassandra-cluster:
    container_name: cassandra-cluster
    restart: always
    image: ce5334a7b86c
    networks:
      - isolation-network
    volumes:
      - cassandra-volume:/var/lib/cassandra
volumes:
  cassandra-volume:
