apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: ingest
  name: ingest
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ingest
    spec:
      containers:
      - image: ingest
        name: ingest
        ports:
        - containerPort: 4003
        resources: {}
      restartPolicy: Always
status: {}
