apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: packager
  name: packager
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: packager
    spec:
      containers:
      - image: packager
        name: packager
        ports:
        - containerPort: 4004
        resources: {}
      restartPolicy: Always
status: {}
