apiVersion: v1
kind: Service
metadata:
  name: history-retriever-service
  namespace: default
spec:
  selector:
    # matches with Deployment spec.selector.matchLabels
    app: history-retriever
  ports:
    - port: 4002
      targetPort: 4002