apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-end-deployment
  namespace: default
  labels:
    app: back-end
spec:
  replicas: 3
  selector:
    matchLabels:
      app: back-end
  template:
    metadata:
      labels:
        app: back-end
    spec:
      containers:
      - name: back-end
        image: s3249212/back-end:latest
        ports:
          - containerPort: 5000