apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: default
spec:
  selector:
    # matches with Deployment spec.selector.matchLabels
    app: db
  ports:
    - port: 27019
      targetPort: 27019