apiVersion: v1
kind: Service
metadata:
  name: front-end-service
  namespace: default
spec:
  selector:
    # matches with Deployment spec.selector.matchLabels
    app: front-end
  ports:
    - port: 80
      targetPort: 80