apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: default
spec:
  selector:
    # matches with Deployment spec.selector.matchLabels
    app: chat
  ports:
    - port: 4001
      targetPort: 4001