apiVersion: v1
kind: Service
metadata:
  name: ingestion-service
  namespace: default
spec:
  selector:
    # matches with Deployment spec.selector.matchLabels
    app: ingestion
  ports:
    - port: 4003
      targetPort: 4003