apiVersion: v1
kind: Service
metadata:
  name: packager-service
  namespace: default
spec:
  selector:
    # matches with Deployment spec.selector.matchLabels
    app: packager
  ports:
    - port: 4004
      targetPort: 4004